// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: opus_frame.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaggedOpusFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemId                 uint32                 `protobuf:"varint,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Tgid                     uint32                 `protobuf:"varint,2,opt,name=tgid,proto3" json:"tgid,omitempty"`
	SrcId                    uint32                 `protobuf:"varint,3,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	SampleLengthMicroseconds uint32                 `protobuf:"varint,4,opt,name=sample_length_microseconds,json=sampleLengthMicroseconds,proto3" json:"sample_length_microseconds,omitempty"`
	Ts                       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	FrameNumber              uint64                 `protobuf:"varint,6,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Data                     []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TaggedOpusFrame) Reset() {
	*x = TaggedOpusFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opus_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaggedOpusFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedOpusFrame) ProtoMessage() {}

func (x *TaggedOpusFrame) ProtoReflect() protoreflect.Message {
	mi := &file_opus_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedOpusFrame.ProtoReflect.Descriptor instead.
func (*TaggedOpusFrame) Descriptor() ([]byte, []int) {
	return file_opus_frame_proto_rawDescGZIP(), []int{0}
}

func (x *TaggedOpusFrame) GetSystemId() uint32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *TaggedOpusFrame) GetTgid() uint32 {
	if x != nil {
		return x.Tgid
	}
	return 0
}

func (x *TaggedOpusFrame) GetSrcId() uint32 {
	if x != nil {
		return x.SrcId
	}
	return 0
}

func (x *TaggedOpusFrame) GetSampleLengthMicroseconds() uint32 {
	if x != nil {
		return x.SampleLengthMicroseconds
	}
	return 0
}

func (x *TaggedOpusFrame) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TaggedOpusFrame) GetFrameNumber() uint64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *TaggedOpusFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_opus_frame_proto protoreflect.FileDescriptor

var file_opus_frame_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x70, 0x75, 0x73, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x74, 0x75, 0x72, 0x62, 0x69, 0x6e, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x01, 0x0a,
	0x0f, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x4f, 0x70, 0x75, 0x73, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x67, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x67, 0x69,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x1a, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x18, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x72, 0x61, 0x73, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x69, 0x6e, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_opus_frame_proto_rawDescOnce sync.Once
	file_opus_frame_proto_rawDescData = file_opus_frame_proto_rawDesc
)

func file_opus_frame_proto_rawDescGZIP() []byte {
	file_opus_frame_proto_rawDescOnce.Do(func() {
		file_opus_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_opus_frame_proto_rawDescData)
	})
	return file_opus_frame_proto_rawDescData
}

var file_opus_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_opus_frame_proto_goTypes = []interface{}{
	(*TaggedOpusFrame)(nil),       // 0: turbine.TaggedOpusFrame
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_opus_frame_proto_depIdxs = []int32{
	1, // 0: turbine.TaggedOpusFrame.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_opus_frame_proto_init() }
func file_opus_frame_proto_init() {
	if File_opus_frame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opus_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaggedOpusFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opus_frame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opus_frame_proto_goTypes,
		DependencyIndexes: file_opus_frame_proto_depIdxs,
		MessageInfos:      file_opus_frame_proto_msgTypes,
	}.Build()
	File_opus_frame_proto = out.File
	file_opus_frame_proto_rawDesc = nil
	file_opus_frame_proto_goTypes = nil
	file_opus_frame_proto_depIdxs = nil
}
